name: feature_deploy  
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v3
    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: 'adopt'
        java-version: '17'
        cache: 'gradle'
    - run: ./gradlew clean build
  docker:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'
          cache: 'gradle'
      - name: Create docker image
        run: ./gradlew jib -Djib.to.auth.username=ricardosanfelice -Djib.to.auth.password=${{secrets.DOCKER_TOKEN}} -Djib.to.tags="$(echo ${GITHUB_REF#refs/heads/})_$(git rev-parse --short HEAD)"
  deploy:
    needs: docker
    runs-on: ubuntu-latest
    steps:
      - name: Deploy dev
        run: |
          curl \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer 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"\
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/sanfelice/kubernetes_projects/actions/main.yml/main.yml/dispatches \
            -d '{"ref":"dev","inputs":{"app":"kubernetes_app","environment":"dev", "image":"ricardosanfelice/kubernetes_app:$(echo ${GITHUB_REF#refs/heads/})_$(git rev-parse --short HEAD)"}}'
